packages:
  - apps/*
  - packages/*
onlyBuiltDependencies:
  - "@biomejs/biome"
  - "@parcel/watcher"
  - esbuild
  - sharp
  - workerd
catalog:
  "@ai-sdk/openai": ^1.3.3
  "@biomejs/biome": 1.9.4
  "@cloudflare/workers-types": ^4.20250214.0
  "@tanstack/react-router": ^1.114.29
  "@tanstack/react-start": ^1.114.29
  "@types/react": ^19.0.12
  "@types/react-dom": ^19.0.4
  "@vitejs/plugin-react": ^4.3.4
  ai: ^4.2.6
  hono: ^4.7.5
  react: ^19.0.0
  react-dom: ^19.0.0
  turbo: ^2.4.4
  typescript: ^5.8.2
  vinxi: ^0.5.3
  vite-tsconfig-paths: ^5.1.4
  wrangler: ^4.4.0
  zod: ^3.24.2
