packages:
  - apps/*
  - packages/*
onlyBuiltDependencies:
  - "@biomejs/biome"
  - "@parcel/watcher"
  - esbuild
  - sharp
  - workerd
catalog:
  "@ai-sdk/openai": ^1.3.7
  "@ai-sdk/react": ^1.2.6
  "@biomejs/biome": ^1.9.4
  "@chromatic-com/storybook": ^3.2.6
  "@heroicons/react": ^2.2.0
  "@neondatabase/serverless": ^1.0.0
  "@storybook/addon-essentials": ^8.6.12
  "@storybook/addon-interactions": ^8.6.12
  "@storybook/addon-themes": ^8.6.12
  "@storybook/blocks": ^8.6.12
  "@storybook/react": ^8.6.12
  "@storybook/react-vite": ^8.6.12
  "@storybook/test": ^8.6.12
  "@tailwindcss/language-server": ^0.14.13
  "@tailwindcss/vite": ^4.1.3
  "@tanstack/react-router": ^1.115.0
  "@tanstack/react-start": ^1.115.1
  "@types/node": ^22.14.0
  "@types/react": ^19.1.0
  "@types/react-dom": ^19.1.1
  "@vitejs/plugin-react": ^4.3.4
  ai: ^4.3.2
  better-auth: ^1.2.5
  clsx: ^2.1.1
  dotenv: ^16.4.7
  drizzle-kit: ^0.30.6
  drizzle-orm: ^0.41.0
  hono: ^4.7.5
  lucide-react: ^0.487.0
  motion: ^12.6.3
  react: ^19.1.0
  react-aria: ^3.38.1
  react-aria-components: ^1.7.1
  react-dom: ^19.1.0
  storybook: ^8.6.12
  tailwind-variants: ^1.0.0
  tailwindcss: ^4.1.3
  tailwindcss-animate: ^1.0.7
  tailwindcss-react-aria-components: ^2.0.0
  taze: ^19.0.4
  turbo: ^2.5.0
  typescript: ^5.8.3
  vinxi: ^0.5.3
  vite: ^6.2.5
  vite-tsconfig-paths: ^5.1.4
  wrangler: ^4.7.2
  zod: ^3.24.2
