packages:
  - apps/*
  - packages/*
onlyBuiltDependencies:
  - "@biomejs/biome"
  - "@parcel/watcher"
  - esbuild
  - sharp
  - workerd
catalog:
  "@ai-sdk/anthropic": ^1.2.10
  "@ai-sdk/openai": ^1.3.20
  "@ai-sdk/react": ^1.2.9
  "@biomejs/biome": ^1.9.4
  "@chromatic-com/storybook": ^3.2.6
  "@heroicons/react": ^2.2.0
  "@hono/zod-validator": ^0.4.3
  "@neondatabase/serverless": ^1.0.0
  "@storybook/addon-essentials": ^8.6.12
  "@storybook/addon-interactions": ^8.6.12
  "@storybook/addon-themes": ^8.6.12
  "@storybook/blocks": ^8.6.12
  "@storybook/react": ^8.6.12
  "@storybook/react-vite": ^8.6.12
  "@storybook/test": ^8.6.12
  "@tailwindcss/vite": ^4.1.4
  "@tanstack/react-query": ^5.74.7
  "@tanstack/react-query-devtools": ^5.74.7
  "@tanstack/react-router": ^1.117.1
  "@tanstack/react-router-with-query": ^1.117.1
  "@tanstack/react-start": ^1.118.0
  "@tanstack/router-plugin": ^1.117.2
  "@types/node": ^22.15.2
  "@types/react": ^19.1.2
  "@types/react-dom": ^19.1.2
  "@vitejs/plugin-react": ^4.4.1
  ai: ^4.3.10
  better-auth: ^1.2.7
  clsx: ^2.1.1
  dotenv: ^16.5.0
  drizzle-kit: ^0.30.6
  drizzle-orm: ^0.41.0
  hono: ^4.7.7
  lucide-react: ^0.487.0
  motion: ^12.9.2
  react: ^19.1.0
  react-aria: ^3.39.0
  react-aria-components: ^1.8.0
  react-dom: ^19.1.0
  storybook: ^8.6.12
  tailwind-variants: ^1.0.0
  tailwindcss: ^4.1.4
  tailwindcss-animate: ^1.0.7
  tailwindcss-react-aria-components: ^2.0.0
  taze: ^19.0.4
  turbo: ^2.5.2
  typescript: ^5.8.3
  vinxi: ^0.5.6
  vite: ^6.3.3
  vite-plugin-dts: ^4.5.3
  vite-tsconfig-paths: ^5.1.4
  wrangler: ^4.13.2
  zod: ^3.24.3
