packages:
  - apps/*
  - packages/*
catalog:
  "@ai-sdk/anthropic": ^1.2.12
  "@ai-sdk/openai": ^1.3.22
  "@ai-sdk/react": ^1.2.12
  "@ai-sdk/ui-utils": "^1.2.11"
  "@biomejs/biome": ^1.9.4
  "@chromatic-com/storybook": ^3.2.6
  "@heroicons/react": ^2.2.0
  "@hono/zod-validator": ^0.5.0
  "@neondatabase/serverless": ^1.0.0
  "@storybook/addon-essentials": ^8.6.14
  "@storybook/addon-interactions": ^8.6.14
  "@storybook/addon-themes": ^8.6.14
  "@storybook/blocks": ^8.6.14
  "@storybook/react": ^8.6.14
  "@storybook/react-vite": ^8.6.14
  "@storybook/test": ^8.6.14
  "@tailwindcss/vite": ^4.1.7
  "@tanstack/react-query": ^5.76.2
  "@tanstack/react-query-devtools": ^5.76.2
  "@tanstack/react-router": ^1.120.7
  "@tanstack/react-router-with-query": ^1.120.7
  "@tanstack/react-start": ^1.120.7
  "@tanstack/router-plugin": ^1.120.7
  "@types/node": ^22.15.21
  "@types/react": ^19.1.5
  "@types/react-dom": ^19.1.5
  "@vitejs/plugin-react": ^4.4.1
  ai: ^4.3.16
  better-auth: ^1.2.8
  clsx: ^2.1.1
  dotenv: ^16.5.0
  drizzle-kit: ^0.31.1
  drizzle-orm: ^0.43.1
  hono: ^4.7.10
  lucide-react: ^0.511.0
  motion: ^12.12.1
  react: ^19.1.0
  react-aria: ^3.40.0
  react-aria-components: ^1.9.0
  react-dom: ^19.1.0
  storybook: ^8.6.14
  tailwind-variants: ^1.0.0
  tailwindcss: ^4.1.7
  tailwindcss-animate: ^1.0.7
  tailwindcss-react-aria-components: ^2.0.0
  taze: ^19.1.0
  turbo: ^2.5.3
  typescript: ^5.8.3
  vinxi: ^0.5.6
  vite: ^6.3.5
  vite-plugin-dts: ^4.5.4
  vite-tsconfig-paths: ^5.1.4
  wrangler: ^4.16.1
  zod: ^3.25.23
onlyBuiltDependencies:
  - "@biomejs/biome"
  - "@parcel/watcher"
  - "@tailwindcss/oxide"
  - esbuild
  - sharp
  - workerd
