packages:
  - apps/*
  - packages/*
onlyBuiltDependencies:
  - "@biomejs/biome"
  - "@parcel/watcher"
  - esbuild
  - sharp
  - workerd
catalog:
  "@ai-sdk/anthropic": ^1.2.11
  "@ai-sdk/openai": ^1.3.22
  "@ai-sdk/react": ^1.2.12
  "@biomejs/biome": ^1.9.4
  "@chromatic-com/storybook": ^3.2.6
  "@heroicons/react": ^2.2.0
  "@hono/zod-validator": ^0.4.3
  "@neondatabase/serverless": ^1.0.0
  "@storybook/addon-essentials": ^8.6.12
  "@storybook/addon-interactions": ^8.6.12
  "@storybook/addon-themes": ^8.6.12
  "@storybook/blocks": ^8.6.12
  "@storybook/react": ^8.6.12
  "@storybook/react-vite": ^8.6.12
  "@storybook/test": ^8.6.12
  "@tailwindcss/vite": ^4.1.5
  "@tanstack/react-query": ^5.75.5
  "@tanstack/react-query-devtools": ^5.75.5
  "@tanstack/react-router": ^1.120.2
  "@tanstack/react-router-with-query": ^1.120.2
  "@tanstack/react-start": ^1.120.2
  "@tanstack/router-plugin": ^1.120.2
  "@types/node": ^22.15.15
  "@types/react": ^19.1.3
  "@types/react-dom": ^19.1.3
  "@vitejs/plugin-react": ^4.4.1
  ai: ^4.3.15
  better-auth: ^1.2.7
  clsx: ^2.1.1
  dotenv: ^16.5.0
  drizzle-kit: ^0.30.6
  drizzle-orm: ^0.41.0
  hono: ^4.7.8
  lucide-react: ^0.487.0
  motion: ^12.10.1
  react: ^19.1.0
  react-aria: ^3.39.0
  react-aria-components: ^1.8.0
  react-dom: ^19.1.0
  storybook: ^8.6.12
  tailwind-variants: ^1.0.0
  tailwindcss: ^4.1.5
  tailwindcss-animate: ^1.0.7
  tailwindcss-react-aria-components: ^2.0.0
  taze: ^19.1.0
  turbo: ^2.5.3
  typescript: ^5.8.3
  vinxi: ^0.5.6
  vite: ^6.3.5
  vite-plugin-dts: ^4.5.3
  vite-tsconfig-paths: ^5.1.4
  wrangler: ^4.14.3
  zod: ^3.24.4
